### ISSUE TITLE
Feature: Delay running scrub every N days

### ISSUE THREAD

**Issue by jack-mil** [firasdib/snapper#12]
Hi there! I have been using this snapraid runner for a while, I really like the Discord notifications. I have made some local changes to the script to support not running the scrub job every time (I don't need to scrub every night). This is a feature that some other snapraid runner/manager scripts have. Would you be interested in including it? I can open a PR, but wasn't sure if this was a feature you were interested in
```
Delayed scrub is enabled.
Number of delayed runs has reached/exceeded threshold (3). A SCRUB job will run.
Running scrub job...
```

**Comment by firasdib** [comment]
PRs are always welcome! 🤩Vänliga hälsningar / Best regards,Firas DibOn 3 Jun 2024, at 01:26, jack-mil ***@***.***> wrote:﻿
Hi there! I have been using this snapraid runner for a while, I really like the Discord notifications. I have made some local changes to the script to support not running the scrub job every time (I don't need to scrub every night). This is a feature that some other snapraid runner/manager scripts have. Would you be interested in including it? I can open a PR, but didn't know if you wanted contributions on this project
Delayed scrub is enabled.
Number of delayed runs has reached/exceeded threshold (3). A SCRUB job will run.
Running scrub job...
